export * from "./navBar";
export * from "./hero";
export * from "./services";
export * from "./features";
export * from "./pricing";
export * from "./testimonials";
export * from "./blog";
export * from "./contactUs";
export * from "./footer";
